name: Commitlint

on:
  pull_request:
    paths:
      - "website/**"
      - ".github/workflows/commitlint.yaml"

jobs:
  lint-commit-messages:
    name: Lint commit messages
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: paschdan/semantic-pullrequest-action@v1
        with:
          config_file: ./commitlint.config.ts
          check_title: false
          create_comment: false
  block-autosquash-commits:
    name: Block autosquash commits
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
